plugins {
    id 'com.android.application'
}

android {
    namespace 'pg.medtrack.png'
    compileSdk 35

    defaultConfig {
        applicationId 'pg.medtrack.png.v2'
        minSdk 23
        targetSdk 35
        versionCode 200
        versionName '2.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            versionNameSuffix '-debug'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}
